apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vkpr-vault-backend
spec:
  provider:
    vault:
      server: "http://vkpr.vault:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vkpr-vault-token"
          key: "token"
          