apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: vkpr-vault-cluster-external-secret
spec:
  externalSecretName: "vkpr-es-created"
  namespaceSelector:
    matchLabels: 
      app.kubernetes.io/managed-by: vkpr
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: vkpr-vault-backend
      kind: ClusterSecretStore
    refreshInterval: "1h"
    target:
      name: my-secret
    data:
      - secretKey: path
        remoteRef:
          key: key