apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vkpr-vault-es
  labels:
    app.kubernetes.io/managed-by: vkpr
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vkpr-vault-backend
    kind: SecretStore
  target:
    name: vkpr-vault-es-secret
  data:
  - secretKey: vkpr-vault-es-key
    remoteRef:
      key: path
      property: key