{
 "title": "Jaeger",
 "description": "Dashboard for monitoring jaeger running in a k8s environment. Works with 1.9+. Feedbacks? Please send to luong.vo@employmenthero.com",
 "tags": [ "jaeger" ],
 "time": { "from": "2022-08-08T18:36:20.808Z", "to": "2022-08-08T18:40:47.914Z" },
 "panels": [
  { "title": "Jaeger Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average request latency (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(jaeger_rpc_request_latency_sum / jaeger_rpc_request_latency_count)*1000"
    }
   ]
  },
  {
   "title": "Requests/min (All requests)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces\")",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces/-traceID-\")",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services/-service-/operations\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services\")",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  }
 ]
}