#!/usr/bin/env bash

export VKPR_EXTERNAL_DNS_VERSION="1.10.1" \
      VKPR_WHOAMI_VERSION="2.5.0" \
      VKPR_KEYCLOAK_VERSION="10.1.0" \
      VKPR_LOKI_VERSION="2.6.3" \
      VKPR_PROMETHEUS_STACK_VERSION="35.3.0" \
      VKPR_POSTGRESQL_VERSION="11.6.4" \
      VKPR_POSTGRESQL_HA_VERSION="8.2.5" \
      VKPR_INGRESS_NGINX_VERSION="4.0.13" \
      VKPR_CERT_MANAGER_VERSION="v1.9.1" \
      VKPR_KONG_VERSION="2.13.0" \
      VKPR_CONSUL_VERSION="0.38.0" \
      VKPR_VAULT_VERSION="0.22.0" \
      VKPR_ARGOCD_VERSION="4.6.3" \
      VKPR_ARGOCD_ROLLOUTS_VERSION="2.20.0" \
      VKPR_ARGOCD_EVENTS_VERSION="2.0.5" \
      VKPR_ARGOCD_WORKFLOWS_VERSION="0.19.6" \
      VKPR_JAEGER_VERSION="0.56.5" \
      VKPR_MOCKSERVER_VERSION="5.13.2" \
      VKPR_DEVPORTAL_VERSION="0.1.2" \
      VKPR_NEXUS_VERSION="4.14.0" \
      VKPR_EXTERNAL_SECRETS_VERSION="0.6.0" \
      VKPR_REDIS_VERSION="17.3.2"
