#!/usr/bin/env bash

export VKPR_EXTERNAL_DNS_VERSION="1.10.1" \
      VKPR_WHOAMI_VERSION="2.5.0" \
      VKPR_KEYCLOAK_VERSION="9.6.8" \
      VKPR_LOKI_VERSION="2.6.3" \
      VKPR_PROMETHEUS_STACK_VERSION="35.3.0" \
      VKPR_POSTGRESQL_VERSION="11.6.4" \
      VKPR_POSTGRESQL_HA_VERSION="8.2.5" \
      VKPR_INGRESS_NGINX_VERSION="4.0.13" \
      VKPR_CERT_MANAGER_VERSION="v1.9.1" \
      VKPR_KONG_VERSION="2.9.1" \
      VKPR_CONSUL_VERSION="0.38.0" \
      VKPR_VAULT_VERSION="0.19.0" \
      VKPR_ARGOCD_VERSION="4.6.3" \
      VKPR_JAEGER_VERSION="0.56.5" \
      VKPR_MOCKSERVER_VERSION="5.13.2" \
      VKPR_DEVPORTAL_VERSION="0.1.2"
