#!/usr/bin/env bash

export VKPR_EXTERNAL_DNS_VERSION="1.10.1" \
      VKPR_WHOAMI_VERSION="2.5.0" \
      VKPR_KEYCLOAK_VERSION="14.1.0" \
      VKPR_LOKI_VERSION="2.8.7" \
      VKPR_PROMETHEUS_STACK_VERSION="45.20.0" \
      VKPR_POSTGRESQL_VERSION="12.5.1" \
      VKPR_POSTGRESQL_HA_VERSION="11.6.1" \
      VKPR_INGRESS_NGINX_VERSION="4.0.13" \
      VKPR_CERT_MANAGER_VERSION="v1.9.1" \
      VKPR_KONG_VERSION="2.19.0" \
      VKPR_CONSUL_VERSION="0.38.0" \
      VKPR_VAULT_VERSION="0.22.0" \
      VKPR_ARGOCD_VERSION="4.6.3" \
      VKPR_ARGOCD_ROLLOUTS_VERSION="2.20.0" \
      VKPR_ARGOCD_EVENTS_VERSION="2.0.5" \
      VKPR_ARGOCD_WORKFLOWS_VERSION="0.19.6" \
      VKPR_JAEGER_VERSION="0.69.1" \
      VKPR_MOCKSERVER_VERSION="5.14.0" \
      VKPR_DEVPORTAL_VERSION="0.3.2" \
      VKPR_NEXUS_VERSION="4.14.0" \
      VKPR_EXTERNAL_SECRETS_VERSION="0.6.0" \
      VKPR_REDIS_VERSION="17.3.2" \
      VKPR_EFS_EKS="2.3.5" \
      VKPR_OTEL_VERSION="0.24.0"
