apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: certmanager-issuer
  secretName: wildcard-certificate
