#!/bin/bash

export VKPR_EXTERNAL_DNS_VERSION="6.4.3" \
      VKPR_WHOAMI_VERSION="2.5.0" \
      VKPR_KEYCLOAK_VERSION="9.0.4" \
      VKPR_LOKI_VERSION="2.6.3" \
      VKPR_PROMETHEUS_STACK_VERSION="35.3.0" \
      VKPR_POSTGRES_VERSION="10.12.3" \
      VKPR_INGRESS_NGINX_VERSION="4.0.13" \
      VKPR_CERT_VERSION="v1.8.0" \
      VKPR_KONG_VERSION="2.6.4" \
      VKPR_CONSUL_VERSION="0.38.0" \
      VKPR_VAULT_VERSION="0.19.0" \
      VKPR_ARGOCD_VERSION="3.29.4" \
      VKPR_ARGOCD_ADDON_APPLICATIONSET_VERSION="1.9.1" \
      VKPR_JAEGER_VERSION="0.56.5" \
      VKPR_MOCKSERVER_VERSION="5.13.2"
