{
 "title": "Kong Simplified Metrics",
 "description": "VKPR Exported dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kong_nginx_http_current_connections,instance)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kong_http_consumer_status, exported_service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(kong_http_consumer_status, route)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(kong_http_consumer_status, consumer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed RPS per route by status code",
     "type": "graph",
     "description": "Requests on the 400 and 500 http status code range",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{exported_service=~\"$service\", instance=~\"$instance\", code=~\"4..|5..\"}[1m])) by (code, exported_service)",
       "legendFormat": "service: {{exported_service}} - code: {{code}}"
      }
     ]
    },
    {
     "title": "Successful RPS per route by status code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{route=~\"$route\", instance=~\"$instance\",  code=~\"2..\"}[1m])) by (code, route)",
       "legendFormat": "route: {{route}} - code: {{code}}"
      }
     ]
    },
    {
     "title": "Total RPS per route by status code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{route=~\"$route\", instance=~\"$instance\"}[1m])) by (code, route)",
       "legendFormat": "route: {{route}} - code: {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests per Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed RPS per service by status code",
     "type": "graph",
     "description": "Requests on the 400 and 500 http status code range",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{exported_service=~\"$service\", instance=~\"$instance\", code=~\"4..|5..\"}[1m])) by (code, exported_service)",
       "legendFormat": "service: {{exported_service}} - code: {{code}}"
      }
     ]
    },
    {
     "title": "Successful RPS per service by status code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{exported_service=~\"$service\", instance=~\"$instance\", code=~\"2..\"}[1m])) by (code, exported_service)",
       "legendFormat": "service: {{exported_service}} - code: {{code}}"
      }
     ]
    },
    {
     "title": "Total RPS per service by status code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{exported_service=~\"$service\", instance=~\"$instance\"}[1m])) by (code, exported_service)",
       "legendFormat": "service: {{exported_service}} - code: {{code}}"
      }
     ]
    }
   ]
  },
  { "title": "Consumer Requests per Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Failed RPS per consumer by service and status code",
   "type": "graph",
   "description": "Requests on the 400 and 500 http status code range",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{exported_service=~\"$service\", instance=~\"$instance\", consumer=~\"$consumer\", code=~\"4..|5..\"}[1m])) by (consumer, code, exported_service)",
     "legendFormat": "consumer:{{consumer}} - service: {{exported_service}} - code: {{code}}"
    }
   ]
  },
  {
   "title": "Successful RPS per consumer by service and status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{exported_service=~\"$service\", instance=~\"$instance\", consumer=~\"$consumer\", code=~\"2..\"}[1m])) by (consumer, code, exported_service)",
     "legendFormat": "consumer:{{consumer}} - service: {{exported_service}} - code: {{code}}"
    }
   ]
  },
  {
   "title": "Total RPS per consumer by service and status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{exported_service=~\"$service\", instance=~\"$instance\", consumer=~\"$consumer\"}[1m])) by (consumer, code, exported_service)",
     "legendFormat": "consumer:{{consumer}} - service: {{exported_service}} - code: {{code}}"
    }
   ]
  },
  { "title": "Consumer Requests per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Failed RPS per consumer by route and status code",
   "type": "graph",
   "description": "Requests on the 400 and 500 http status code range",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{route=~\"$route\", instance=~\"$instance\", consumer=~\"$consumer\", code=~\"4..|5..\"}[1m])) by (consumer, code, route)",
     "legendFormat": "consumer:{{consumer}} - route: {{route}} - code: {{code}}"
    }
   ]
  },
  {
   "title": "Successful RPS per consumer by route and status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{route=~\"$route\", instance=~\"$instance\", consumer=~\"$consumer\", code=~\"2..\"}[1m])) by (consumer, code, route)",
     "legendFormat": "consumer:{{consumer}} - route: {{route}} - code: {{code}}"
    }
   ]
  },
  {
   "title": "Total RPS per consumer by route and status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{route=~\"$route\", instance=~\"$instance\", consumer=~\"$consumer\"}[1m])) by (consumer, code, route)",
     "legendFormat": "consumer:{{consumer}} - route: {{route}} - code: {{code}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Failed RPS per route/service by status code",
   "type": "graph",
   "description": "Requests on the 400 and 500 http status code range",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{instance=~\"$instance\", code=~\"4..|5..\"}[1m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_status{instance=~\"$instance\", code!~\"2..\"}[1m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"kong\",instance=~\"$instance\", exported_service=~\"$service\"}[1m])) by (exported_service,le))",
     "legendFormat": "service: {{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Time per service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\",instance=~\"$instance\", exported_service=~\"$service\"}[1m])) by (exported_service,le))",
     "legendFormat": "service: {{exported_service}}"
    }
   ]
  },
  {
   "title": "Request Time per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"request\",route=~\"$route\",instance=~\"$instance\"}[1m])) by (route,le))",
     "legendFormat": "route: {{route}}"
    }
   ]
  },
  {
   "title": "Total RPS by Consumer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(kong_http_consumer_status{consumer=~\"$consumer\"}[1m])) by (consumer)",
     "legendFormat": "consumer: {{consumer}}"
    }
   ]
  }
 ]
}