name: Lint code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.5

      - name: List changes in workflow
        if: contains(steps.changed-files.outputs.all_changed_files, 'blank.yml')
        run: |
          echo "alterando workflow"
      - name: List changes in whoami
        if: contains(steps.changed-files.outputs.all_changed_files, 'whoami')
        env:
          WHOAMI_FILES: ${{ contains(steps.changed-files.outputs.all_changed_files, 'whoami') }}
        run: |
          for file in $WHOAMI_FILES; do
            shellcheck $file
          done
