name: Lint code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get existing Files
        id: existing-files
        run: |
          echo "::set-output name=get-changed-files::$(git ls-files | grep .sh)\n"
      - name: Files
        run: |
          for file in ${{ steps.existing-files.outputs.get-changed-files }}; do
            echo "$file exists"
          done
