name: Lint code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          additional_files: .
          ignore: /
          severity: error
          check_together: false
          scandir: .
          disable_matcher: false
          format: gcc
