name: Lint code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.5
      - name: List changes in whoami
        if: contains(steps.changed-files.outputs.all_changed_files, 'whoami')
        run: |
          for file in ${{steps.changed-files.outputs.all_changed_files}}; do
            if [[ $(echo $file | grep whoami) ]]; then
              shellcheck $file
            fi
          done
      - name: List changes in workflow
        if: contains(steps.changed-files.outputs.all_changed_files, 'blank.yml')
        run: |
          WORKFLOW_FILE="$(${{steps.changed-files.outputs.all_changed_files}} | grep blank.yml)"
          echo "$WORKFLOW_FILE"
