name: Lint code

on:
  push:
    branches: [ main ]
    paths:
      - vkpr/**
  pull_request:
    branches: [ main ]
    paths:
      - vkpr/**

jobs:
  lint:
    name: Lint shell files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.5
        with: 
          files: |
            *.sh
            **/*.sh

      - name: Lint new shell files
        if: ${{steps.changed-files.outputs.added_files}} == 'true'
        run: |
          for file in ${{steps.changed-files.outputs.added_files}}; do
            if [[ $(echo $file | grep .sh) ]]; then
              shellcheck $file
            fi
          done

      - name: Lint existing shell files
        if: ${{steps.changed-files.outputs.modified_files}} == 'true'
        run: |
          shellcheck ${{steps.changed-files.outputs.all_changed_files}}
